condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.9/mkShapes__JJH16__ALL__VgS.9.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.8/mkShapes__JJH16__ALL__VgS.8.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.7/mkShapes__JJH16__ALL__VgS.7.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.6/mkShapes__JJH16__ALL__VgS.6.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.5/mkShapes__JJH16__ALL__VgS.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.4/mkShapes__JJH16__ALL__VgS.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.3/mkShapes__JJH16__ALL__VgS.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.2/mkShapes__JJH16__ALL__VgS.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.29/mkShapes__JJH16__ALL__VgS.29.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.28/mkShapes__JJH16__ALL__VgS.28.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.27/mkShapes__JJH16__ALL__VgS.27.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.26/mkShapes__JJH16__ALL__VgS.26.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.25/mkShapes__JJH16__ALL__VgS.25.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.24/mkShapes__JJH16__ALL__VgS.24.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.23/mkShapes__JJH16__ALL__VgS.23.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.22/mkShapes__JJH16__ALL__VgS.22.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.21/mkShapes__JJH16__ALL__VgS.21.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.20/mkShapes__JJH16__ALL__VgS.20.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.1/mkShapes__JJH16__ALL__VgS.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.19/mkShapes__JJH16__ALL__VgS.19.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.18/mkShapes__JJH16__ALL__VgS.18.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.17/mkShapes__JJH16__ALL__VgS.17.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.16/mkShapes__JJH16__ALL__VgS.16.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.15/mkShapes__JJH16__ALL__VgS.15.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.14/mkShapes__JJH16__ALL__VgS.14.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.13/mkShapes__JJH16__ALL__VgS.13.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.12/mkShapes__JJH16__ALL__VgS.12.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.11/mkShapes__JJH16__ALL__VgS.11.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.10/mkShapes__JJH16__ALL__VgS.10.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/VgS.0/mkShapes__JJH16__ALL__VgS.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.9/mkShapes__JJH16__ALL__Vg.9.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.8/mkShapes__JJH16__ALL__Vg.8.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.7/mkShapes__JJH16__ALL__Vg.7.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.6/mkShapes__JJH16__ALL__Vg.6.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.5/mkShapes__JJH16__ALL__Vg.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.59/mkShapes__JJH16__ALL__Vg.59.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.58/mkShapes__JJH16__ALL__Vg.58.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.57/mkShapes__JJH16__ALL__Vg.57.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.56/mkShapes__JJH16__ALL__Vg.56.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.55/mkShapes__JJH16__ALL__Vg.55.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.54/mkShapes__JJH16__ALL__Vg.54.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.53/mkShapes__JJH16__ALL__Vg.53.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.52/mkShapes__JJH16__ALL__Vg.52.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.51/mkShapes__JJH16__ALL__Vg.51.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.50/mkShapes__JJH16__ALL__Vg.50.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.4/mkShapes__JJH16__ALL__Vg.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.49/mkShapes__JJH16__ALL__Vg.49.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.48/mkShapes__JJH16__ALL__Vg.48.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.47/mkShapes__JJH16__ALL__Vg.47.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.46/mkShapes__JJH16__ALL__Vg.46.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.45/mkShapes__JJH16__ALL__Vg.45.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.44/mkShapes__JJH16__ALL__Vg.44.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.43/mkShapes__JJH16__ALL__Vg.43.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.42/mkShapes__JJH16__ALL__Vg.42.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.41/mkShapes__JJH16__ALL__Vg.41.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.40/mkShapes__JJH16__ALL__Vg.40.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.3/mkShapes__JJH16__ALL__Vg.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.39/mkShapes__JJH16__ALL__Vg.39.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.38/mkShapes__JJH16__ALL__Vg.38.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.37/mkShapes__JJH16__ALL__Vg.37.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.36/mkShapes__JJH16__ALL__Vg.36.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.35/mkShapes__JJH16__ALL__Vg.35.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.34/mkShapes__JJH16__ALL__Vg.34.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.33/mkShapes__JJH16__ALL__Vg.33.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.32/mkShapes__JJH16__ALL__Vg.32.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.31/mkShapes__JJH16__ALL__Vg.31.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.30/mkShapes__JJH16__ALL__Vg.30.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.2/mkShapes__JJH16__ALL__Vg.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.29/mkShapes__JJH16__ALL__Vg.29.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.28/mkShapes__JJH16__ALL__Vg.28.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.27/mkShapes__JJH16__ALL__Vg.27.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.26/mkShapes__JJH16__ALL__Vg.26.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.25/mkShapes__JJH16__ALL__Vg.25.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.24/mkShapes__JJH16__ALL__Vg.24.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.23/mkShapes__JJH16__ALL__Vg.23.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.22/mkShapes__JJH16__ALL__Vg.22.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.21/mkShapes__JJH16__ALL__Vg.21.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.20/mkShapes__JJH16__ALL__Vg.20.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.1/mkShapes__JJH16__ALL__Vg.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.19/mkShapes__JJH16__ALL__Vg.19.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.18/mkShapes__JJH16__ALL__Vg.18.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.17/mkShapes__JJH16__ALL__Vg.17.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.16/mkShapes__JJH16__ALL__Vg.16.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.15/mkShapes__JJH16__ALL__Vg.15.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.14/mkShapes__JJH16__ALL__Vg.14.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.13/mkShapes__JJH16__ALL__Vg.13.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.12/mkShapes__JJH16__ALL__Vg.12.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.11/mkShapes__JJH16__ALL__Vg.11.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.10/mkShapes__JJH16__ALL__Vg.10.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH16__ALL/Vg.0/mkShapes__JJH16__ALL__Vg.0.jds
