#SMEFT settings
#set ratio range to [0.0,2.0]
mkPlot.py --pycfg=configuration_combined_VBF_INN_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_vbf_hinn_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 2.5 --extraLegend="[D_{VBF}, m_{ll}, D_{0-}, D_{0+}]@@VBF@@D_{CP} < 0@@D_{int} < 0.4"
mkPlot.py --pycfg=configuration_combined_VBF_INP_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_vbf_hinp_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 3.0 --extraLegend="[D_{VBF}, m_{ll}, D_{0-}, D_{0+}]@@VBF@@D_{CP} < 0@@D_{int} > 0.4"
mkPlot.py --pycfg=configuration_combined_VBF_IPN_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_vbf_hipn_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 3.0 --extraLegend="[D_{VBF}, m_{ll}, D_{0-}, D_{0+}]@@VBF@@D_{CP} > 0@@D_{int} < 0.4"
mkPlot.py --pycfg=configuration_combined_VBF_IPP_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_vbf_hipp_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 3.0 --extraLegend="[D_{VBF}, m_{ll}, D_{0-}, D_{0+}]@@VBF@@D_{CP} > 0@@D_{int} > 0.4"

#mkPlot.py --pycfg=configuration_combined_VH_IP_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_vh_hip_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 1.5 --extraLegend="[m_{ll}, D_{0-}, D_{0+}]@@Resolved VH@@D_{CP} > 0"
#mkPlot.py --pycfg=configuration_combined_VH_IN_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_vh_hin_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 1.7 --extraLegend="[m_{ll}, D_{0-}, D_{0+}]@@Resolved VH@@D_{CP} < 0"
#mkPlot.py --pycfg=configuration_combined_VHBoosted_IP_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_Vh_hip_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 5.0 --extraLegend="[m_{ll}, D_{0-}, D_{0+}]@@Boosted VH@@D_{CP} > 0"
#mkPlot.py --pycfg=configuration_combined_VHBoosted_IN_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_Vh_hin_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 5.0 --extraLegend="[m_{ll}, D_{0-}, D_{0+}]@@Boosted VH@@D_{CP} < 0"

#set ratio range to [0.5,1.5]
#mkPlot.py --pycfg=configuration_combined_0j_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_0j_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 5.0 --extraLegend="[m_{ll}, m_{T}^{H}]@@ggF 0-jet"
#mkPlot.py --pycfg=configuration_combined_1j_CWR.py --showIntegralLegend=0 --onlyPlot=cratio --inputFile=output_postFitShapes_Run2_1j_afterRebinBug_H0ALL_fitS.root --fileFormats="png,pdf" --minLogCratio=1.1 --scaleToPlot 5.0 --extraLegend="[m_{ll}, m_{T}^{H}]@@ggF 1-jet"
