# 
# Expanded version of samples.py 
# 
samples['WW'] = { 
     'name'  :  [ 
            'latino_WWTo2L2Nu.root',
     ],  
     'weight'  :   'XSWeight*puW * effTrigW3l * electron_etaW_3l * electron_ptW_3l * veto_EMTFBug  * std_vector_lepton_recoW[0]  * std_vector_lepton_recoW[1]  * std_vector_lepton_recoW[2] *bPogSF_CMVAL*LepSF3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*GenLepMatch2l*METFilter_MC*nllW' ,
}  
   
 samples['ZZ'] = { 
     'name'  :  [ 
            'latino_ZZTo4L__part0.root',
            'latino_ZZTo4L__part1.root',
     ],  
     'weight'  :   'XSWeight*puW * effTrigW3l * electron_etaW_3l * electron_ptW_3l * veto_EMTFBug  * std_vector_lepton_recoW[0]  * std_vector_lepton_recoW[1]  * std_vector_lepton_recoW[2] *bPogSF_CMVAL*LepSF3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*GenLepMatch3l*METFilter_MC' ,
}  
   
 samples['WZ'] = { 
     'name'  :  [ 
            'latino_WZTo3LNu.root',
     ],  
     'weight'  :   'XSWeight*puW * effTrigW3l * electron_etaW_3l * electron_ptW_3l * veto_EMTFBug  * std_vector_lepton_recoW[0]  * std_vector_lepton_recoW[1]  * std_vector_lepton_recoW[2] *bPogSF_CMVAL*LepSF3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*GenLepMatch3l*METFilter_MC' ,
}  
   
 samples['VVV'] = { 
     'name'  :  [ 
            'latino_WZZ.root',
            'latino_ZZZ.root',
            'latino_WWZ.root',
            'latino_WWW.root',
     ],  
     'weight'  :   'XSWeight*puW * effTrigW3l * electron_etaW_3l * electron_ptW_3l * veto_EMTFBug  * std_vector_lepton_recoW[0]  * std_vector_lepton_recoW[1]  * std_vector_lepton_recoW[2] *bPogSF_CMVAL*LepSF3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*GenLepMatch3l*METFilter_MC' ,
}  
   
 samples['Vg'] = { 
     'name'  :  [ 
            'latino_Zg__part0.root',
            'latino_Zg__part1.root',
            'latino_Zg__part2.root',
            'latino_WgStarLNuEE.root',
            'latino_WgStarLNuMuMu.root',
     ],  
     'weight'  :   'XSWeight*puW * effTrigW3l * electron_etaW_3l * electron_ptW_3l * veto_EMTFBug  * std_vector_lepton_recoW[0]  * std_vector_lepton_recoW[1]  * std_vector_lepton_recoW[2] *bPogSF_CMVAL*LepSF3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*GenLepMatch3l*METFilter_MC' ,
}  
   
 samples['WH_htt'] = { 
     'name'  :  [ 
            'latino_HWminusJ_HToTauTau_M125.root',
            'latino_HWplusJ_HToTauTau_M125.root',
            'latino_HZJ_HToTauTau_M125.root',
     ],  
     'weight'  :   'XSWeight*puW * effTrigW3l * electron_etaW_3l * electron_ptW_3l * veto_EMTFBug  * std_vector_lepton_recoW[0]  * std_vector_lepton_recoW[1]  * std_vector_lepton_recoW[2] *bPogSF_CMVAL*LepSF3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*GenLepMatch3l*METFilter_MC' ,
}  
   
 samples['ZH_hww'] = { 
     'name'  :  [ 
            'latino_ggZH_HToWW_M125.root',
            'latino_HZJ_HToWW_M125.root',
     ],  
     'weight'  :   'XSWeight*puW * effTrigW3l * electron_etaW_3l * electron_ptW_3l * veto_EMTFBug  * std_vector_lepton_recoW[0]  * std_vector_lepton_recoW[1]  * std_vector_lepton_recoW[2] *bPogSF_CMVAL*LepSF3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*GenLepMatch3l*METFilter_MC' ,
}  
   
 samples['WH_hww'] = { 
     'name'  :  [ 
            'latino_HWminusJ_HToWW_M125.root',
            'latino_HWplusJ_HToWW_M125.root',
     ],  
     'weight'  :   'XSWeight*puW * effTrigW3l * electron_etaW_3l * electron_ptW_3l * veto_EMTFBug  * std_vector_lepton_recoW[0]  * std_vector_lepton_recoW[1]  * std_vector_lepton_recoW[2] *bPogSF_CMVAL*LepSF3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x*GenLepMatch3l*METFilter_MC' ,
}  
   
 samples['Fake'] = { 
     'name'  :  [ 
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_MuonEG_Run2016B-03Feb2017_ver2-v2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_MuonEG_Run2016C-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016C-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016C-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016C-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016C-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016C-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016C-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_MuonEG_Run2016D-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016D-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016D-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016D-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016D-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016D-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016D-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_MuonEG_Run2016E-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016E-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016E-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016E-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016E-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016E-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016E-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_MuonEG_Run2016F-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016F-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016F-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016F-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016F-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016F-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016F-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_MuonEG_Run2016G-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part3.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part3.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016G-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016G-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016G-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016G-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_MuonEG_Run2016H-03Feb2017_ver2-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part3.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part3.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_MuonEG_Run2016H-03Feb2017_ver3-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleMuon_Run2016H-03Feb2017_ver3-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleMuon_Run2016H-03Feb2017_ver3-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_DoubleEG_Run2016H-03Feb2017_ver3-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__multiFakeW__formulasFAKE__hadd__vh3lFakeSel//latino_SingleElectron_Run2016H-03Feb2017_ver3-v1.root',
     ],  
     'weights'  :  [ 
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
     ],  
     'isData'  :  [ 
            'all',
     ],  
     'weight'  :   'fakeW_ele_mva_90p_Iso2016_mu_cut_Tight80x_3l*veto_EMTFBug*METFilter_DATA' ,
     'FilesPerJob'  :   5 ,
}  
   
 samples['DATA'] = { 
     'name'  :  [ 
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_MuonEG_Run2016B-03Feb2017_ver2-v2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016B-03Feb2017_ver2-v2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016B_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016B-03Feb2017_ver2-v2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_MuonEG_Run2016C-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016C-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016C-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016C-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016C_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016C-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_MuonEG_Run2016D-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016D-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016D-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016D-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016D-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016D-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016D_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016D-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_MuonEG_Run2016E-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016E-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016E-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016E-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016E-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016E-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016E_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016E-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_MuonEG_Run2016F-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016F-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016F-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016F-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016F-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016F-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016F_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016F-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_MuonEG_Run2016G-03Feb2017-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016G-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016G-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016G-03Feb2017-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016G_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016G-03Feb2017-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_MuonEG_Run2016H-03Feb2017_ver2-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part3.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part2.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_MuonEG_Run2016H-03Feb2017_ver3-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleMuon_Run2016H-03Feb2017_ver3-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleMuon_Run2016H-03Feb2017_ver3-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_DoubleEG_Run2016H-03Feb2017_ver3-v1.root',
            '###/eos/cms/store/group/phys_higgs/cmshww/amassiro/Full2016_Apr17/Apr2017_Run2016H_RemAOD/lepSel__EpTCorr__TrigMakerData__cleanTauData__l2loose__hadd__l2tightOR__formulasDATA__vh3lSel//latino_SingleElectron_Run2016H-03Feb2017_ver3-v1.root',
     ],  
     'weights'  :  [ 
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
     ],  
     'isData'  :  [ 
            'all',
     ],  
     'weight'  :   'veto_EMTFBug*METFilter_DATA*LepCut3l__ele_mva_90p_Iso2016__mu_cut_Tight80x' ,
     'FilesPerJob'  :   5 ,
}  
   
 