condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/top.95/mkShapes__JJH18B__ALL__top.95.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/top.78/mkShapes__JJH18B__ALL__top.78.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/top.3/mkShapes__JJH18B__ALL__top.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/top.22/mkShapes__JJH18B__ALL__top.22.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/DY.82/mkShapes__JJH18B__ALL__DY.82.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VZ.5/mkShapes__JJH18B__ALL__VZ.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VZ.28/mkShapes__JJH18B__ALL__VZ.28.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VZ.24/mkShapes__JJH18B__ALL__VZ.24.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VZ.23/mkShapes__JJH18B__ALL__VZ.23.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VZ.1/mkShapes__JJH18B__ALL__VZ.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VZ.0/mkShapes__JJH18B__ALL__VZ.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VVV.1/mkShapes__JJH18B__ALL__VVV.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VgS.9/mkShapes__JJH18B__ALL__VgS.9.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VgS.6/mkShapes__JJH18B__ALL__VgS.6.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VgS.18/mkShapes__JJH18B__ALL__VgS.18.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VgS.16/mkShapes__JJH18B__ALL__VgS.16.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VgS.15/mkShapes__JJH18B__ALL__VgS.15.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/top.247/mkShapes__JJH18B__ALL__top.247.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ggWW.8/mkShapes__JJH18B__ALL__ggWW.8.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ggWW.3/mkShapes__JJH18B__ALL__ggWW.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ggWW.17/mkShapes__JJH18B__ALL__ggWW.17.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ggWW.16/mkShapes__JJH18B__ALL__ggWW.16.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ggWW.10/mkShapes__JJH18B__ALL__ggWW.10.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ggH_hww.45/mkShapes__JJH18B__ALL__ggH_hww.45.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ggH_hww.22/mkShapes__JJH18B__ALL__ggH_hww.22.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_hww.4/mkShapes__JJH18B__ALL__ZH_hww.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_hww.0/mkShapes__JJH18B__ALL__ZH_hww.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_htt.5/mkShapes__JJH18B__ALL__ZH_htt.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_htt.4/mkShapes__JJH18B__ALL__ZH_htt.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_htt.2/mkShapes__JJH18B__ALL__ZH_htt.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_htt.1/mkShapes__JJH18B__ALL__ZH_htt.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_hww.5/mkShapes__JJH18B__ALL__WH_hww.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_hww.4/mkShapes__JJH18B__ALL__WH_hww.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_htt.8/mkShapes__JJH18B__ALL__WH_htt.8.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_htt.3/mkShapes__JJH18B__ALL__WH_htt.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_htt.15/mkShapes__JJH18B__ALL__WH_htt.15.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_htt.11/mkShapes__JJH18B__ALL__WH_htt.11.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05.1/mkShapes__JJH18B__ALL__VBF_H0PHf05.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05.0/mkShapes__JJH18B__ALL__VBF_H0PHf05.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH.3/mkShapes__JJH18B__ALL__VBF_H0PH.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH.1/mkShapes__JJH18B__ALL__VBF_H0PH.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0M_H0PH_M2.0/mkShapes__JJH18B__ALL__VBF_H0M_H0PH_M2.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0M_H0PH_M0.2/mkShapes__JJH18B__ALL__VBF_H0M_H0PH_M0.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0M_H0M_M3.2/mkShapes__JJH18B__ALL__VBF_H0M_H0M_M3.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0M_H0L1_M1.2/mkShapes__JJH18B__ALL__VBF_H0M_H0L1_M1.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1.4/mkShapes__JJH18B__ALL__VBF_H0L1.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1.0/mkShapes__JJH18B__ALL__VBF_H0L1.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/qqH_htt.5/mkShapes__JJH18B__ALL__qqH_htt.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/qqH_htt.4/mkShapes__JJH18B__ALL__qqH_htt.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/qqH_htt.3/mkShapes__JJH18B__ALL__qqH_htt.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0PH_M2.0/mkShapes__JJH18B__ALL__VBF_H0PH_H0PH_M2.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0PH_M0.0/mkShapes__JJH18B__ALL__VBF_H0PH_H0PH_M0.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0M_M2.1/mkShapes__JJH18B__ALL__VBF_H0PH_H0M_M2.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0M_M2.0/mkShapes__JJH18B__ALL__VBF_H0PH_H0M_M2.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0M_M1.3/mkShapes__JJH18B__ALL__VBF_H0PH_H0M_M1.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0M_M0.3/mkShapes__JJH18B__ALL__VBF_H0PH_H0M_M0.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0LZg_M2.1/mkShapes__JJH18B__ALL__VBF_H0PH_H0LZg_M2.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0LZg_M1.3/mkShapes__JJH18B__ALL__VBF_H0PH_H0LZg_M1.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0LZg_M1.0/mkShapes__JJH18B__ALL__VBF_H0PH_H0LZg_M1.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0L1_M2.2/mkShapes__JJH18B__ALL__VBF_H0PH_H0L1_M2.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0L1_M2.0/mkShapes__JJH18B__ALL__VBF_H0PH_H0L1_M2.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PH_H0L1_M1.1/mkShapes__JJH18B__ALL__VBF_H0PH_H0L1_M1.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05_H0PM.1/mkShapes__JJH18B__ALL__VBF_H0PHf05_H0PM.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05_H0PH_M3.1/mkShapes__JJH18B__ALL__VBF_H0PHf05_H0PH_M3.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05_H0PH_M2.1/mkShapes__JJH18B__ALL__VBF_H0PHf05_H0PH_M2.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05_H0PH_M0.2/mkShapes__JJH18B__ALL__VBF_H0PHf05_H0PH_M0.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05_H0PH_M0.1/mkShapes__JJH18B__ALL__VBF_H0PHf05_H0PH_M0.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05_H0M_M3.0/mkShapes__JJH18B__ALL__VBF_H0PHf05_H0M_M3.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05_H0LZg_M3.1/mkShapes__JJH18B__ALL__VBF_H0PHf05_H0LZg_M3.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0PHf05_H0LZg_M0.1/mkShapes__JJH18B__ALL__VBF_H0PHf05_H0LZg_M0.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0Mf05_H0PH_M1.3/mkShapes__JJH18B__ALL__VBF_H0Mf05_H0PH_M1.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0Mf05_H0PH_M1.1/mkShapes__JJH18B__ALL__VBF_H0Mf05_H0PH_M1.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0Mf05_H0M_M3.0/mkShapes__JJH18B__ALL__VBF_H0Mf05_H0M_M3.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0Mf05_H0M_M0.4/mkShapes__JJH18B__ALL__VBF_H0Mf05_H0M_M0.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0Mf05_H0L1_M2.1/mkShapes__JJH18B__ALL__VBF_H0Mf05_H0L1_M2.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0Mf05_H0L1_M0.2/mkShapes__JJH18B__ALL__VBF_H0Mf05_H0L1_M0.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1_H0PM.4/mkShapes__JJH18B__ALL__VBF_H0L1_H0PM.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1_H0PM.0/mkShapes__JJH18B__ALL__VBF_H0L1_H0PM.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1_H0PH_M3.1/mkShapes__JJH18B__ALL__VBF_H0L1_H0PH_M3.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1_H0PH_M1.0/mkShapes__JJH18B__ALL__VBF_H0L1_H0PH_M1.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1_H0M_M3.1/mkShapes__JJH18B__ALL__VBF_H0L1_H0M_M3.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1_H0M_M1.1/mkShapes__JJH18B__ALL__VBF_H0L1_H0M_M1.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1_H0L1_M1.4/mkShapes__JJH18B__ALL__VBF_H0L1_H0L1_M1.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PM_H0PH_M1.1/mkShapes__JJH18B__ALL__WH_H0PM_H0PH_M1.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PM_H0M_M0.2/mkShapes__JJH18B__ALL__WH_H0PM_H0M_M0.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PM_H0L1_M0.3/mkShapes__JJH18B__ALL__WH_H0PM_H0L1_M0.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PM.2/mkShapes__JJH18B__ALL__WH_H0PM.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0PM.3/mkShapes__JJH18B__ALL__WH_H0PH_H0PM.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0PM.1/mkShapes__JJH18B__ALL__WH_H0PH_H0PM.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0M_M1.4/mkShapes__JJH18B__ALL__WH_H0PH_H0M_M1.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0M_M0.1/mkShapes__JJH18B__ALL__WH_H0PH_H0M_M0.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0M_M0.0/mkShapes__JJH18B__ALL__WH_H0PH_H0M_M0.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PHf05.2/mkShapes__JJH18B__ALL__WH_H0PHf05.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH.4/mkShapes__JJH18B__ALL__WH_H0PH.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH.0/mkShapes__JJH18B__ALL__WH_H0PH.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0Mf05_H0PH_M3.4/mkShapes__JJH18B__ALL__WH_H0Mf05_H0PH_M3.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0Mf05_H0PH_M1.4/mkShapes__JJH18B__ALL__WH_H0Mf05_H0PH_M1.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0Mf05_H0L1_M1.2/mkShapes__JJH18B__ALL__WH_H0Mf05_H0L1_M1.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0Mf05_H0L1_M1.0/mkShapes__JJH18B__ALL__WH_H0Mf05_H0L1_M1.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0Mf05.4/mkShapes__JJH18B__ALL__WH_H0Mf05.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0Mf05.2/mkShapes__JJH18B__ALL__WH_H0Mf05.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0Mf05.1/mkShapes__JJH18B__ALL__WH_H0Mf05.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0M.0/mkShapes__JJH18B__ALL__WH_H0M.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1f05_H0M_M1.0/mkShapes__JJH18B__ALL__VBF_H0L1f05_H0M_M1.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1f05_H0LZg_M1.2/mkShapes__JJH18B__ALL__VBF_H0L1f05_H0LZg_M1.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1f05_H0L1_M2.2/mkShapes__JJH18B__ALL__VBF_H0L1f05_H0L1_M2.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1f05_H0L1_M2.1/mkShapes__JJH18B__ALL__VBF_H0L1f05_H0L1_M2.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1f05_H0L1_M1.1/mkShapes__JJH18B__ALL__VBF_H0L1f05_H0L1_M1.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/VBF_H0L1f05_H0L1_M0.2/mkShapes__JJH18B__ALL__VBF_H0L1f05_H0L1_M0.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PM_H0M_M1.1/mkShapes__JJH18B__ALL__ZH_H0PM_H0M_M1.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PM_H0L1_M3.1/mkShapes__JJH18B__ALL__ZH_H0PM_H0L1_M3.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PM_H0L1_M1.0/mkShapes__JJH18B__ALL__ZH_H0PM_H0L1_M1.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH.2/mkShapes__JJH18B__ALL__ZH_H0PH.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0PH_M2.4/mkShapes__JJH18B__ALL__WH_H0PH_H0PH_M2.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0PH_M2.0/mkShapes__JJH18B__ALL__WH_H0PH_H0PH_M2.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0PH_M1.4/mkShapes__JJH18B__ALL__WH_H0PH_H0PH_M1.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0PH_M0.3/mkShapes__JJH18B__ALL__WH_H0PH_H0PH_M0.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0M_M2.4/mkShapes__JJH18B__ALL__WH_H0PH_H0M_M2.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0M_M2.2/mkShapes__JJH18B__ALL__WH_H0PH_H0M_M2.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0M_M2.0/mkShapes__JJH18B__ALL__WH_H0PH_H0M_M2.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0L1_M3.2/mkShapes__JJH18B__ALL__WH_H0PH_H0L1_M3.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0L1_M1.2/mkShapes__JJH18B__ALL__WH_H0PH_H0L1_M1.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/WH_H0PH_H0L1_M0.4/mkShapes__JJH18B__ALL__WH_H0PH_H0L1_M0.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PM_H0LZg_M3.1/mkShapes__JJH18B__ALL__ZH_H0PM_H0LZg_M3.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0PH_M2.4/mkShapes__JJH18B__ALL__ZH_H0PH_H0PH_M2.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0PH_M1.5/mkShapes__JJH18B__ALL__ZH_H0PH_H0PH_M1.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0M_M2.5/mkShapes__JJH18B__ALL__ZH_H0PH_H0M_M2.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0M_M2.0/mkShapes__JJH18B__ALL__ZH_H0PH_H0M_M2.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0M_M0.2/mkShapes__JJH18B__ALL__ZH_H0PH_H0M_M0.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0LZg_M3.5/mkShapes__JJH18B__ALL__ZH_H0PH_H0LZg_M3.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0LZg_M3.4/mkShapes__JJH18B__ALL__ZH_H0PH_H0LZg_M3.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0LZg_M2.3/mkShapes__JJH18B__ALL__ZH_H0PH_H0LZg_M2.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0LZg_M0.4/mkShapes__JJH18B__ALL__ZH_H0PH_H0LZg_M0.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0L1_M0.5/mkShapes__JJH18B__ALL__ZH_H0PH_H0L1_M0.5.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PH_H0L1_M0.2/mkShapes__JJH18B__ALL__ZH_H0PH_H0L1_M0.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PHf05_H0M_M3.2/mkShapes__JJH18B__ALL__ZH_H0PHf05_H0M_M3.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PHf05_H0M_M1.4/mkShapes__JJH18B__ALL__ZH_H0PHf05_H0M_M1.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PHf05_H0L1_M2.4/mkShapes__JJH18B__ALL__ZH_H0PHf05_H0L1_M2.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PHf05_H0L1_M2.0/mkShapes__JJH18B__ALL__ZH_H0PHf05_H0L1_M2.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0M_H0PM.3/mkShapes__JJH18B__ALL__ZH_H0M_H0PM.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0M_H0M_M0.3/mkShapes__JJH18B__ALL__ZH_H0M_H0M_M0.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0M_H0M_M0.0/mkShapes__JJH18B__ALL__ZH_H0M_H0M_M0.0.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0M_H0LZg_M2.2/mkShapes__JJH18B__ALL__ZH_H0M_H0LZg_M2.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0M_H0L1_M2.3/mkShapes__JJH18B__ALL__ZH_H0M_H0L1_M2.3.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0M_H0L1_M2.2/mkShapes__JJH18B__ALL__ZH_H0M_H0L1_M2.2.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0PHf05_H0LZg_M2.4/mkShapes__JJH18B__ALL__ZH_H0PHf05_H0LZg_M2.4.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0L1_H0PM.1/mkShapes__JJH18B__ALL__ZH_H0L1_H0PM.1.jds
condor_submit ../../../../../../../jobs/mkShapes__JJH18B__ALL/ZH_H0L1f05_H0LZg_M3.2/mkShapes__JJH18B__ALL__ZH_H0L1f05_H0LZg_M3.2.jds
