
# loaction of parameterization file: LatinoAnalysis/Gardener/python/data/met
#gardener.py  metXYshift -c 809 -p Spring16_V0_MET_MC_XYshiftMC_PfType1MetLocal.txt latino_stepB_mc_numEvent10000.root latino_MetCorrected_mc_numEvent10000.root
gardener.py  metXYshift -c 809 -p metXYshiftPara_MoriondV1_ftnalPar.txt --sample DY /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW12fb_v2/07Jun2016_spring16_mAODv2_12pXfbm1/MCl2loose__hadd__bSFL2pTEff__l2tight/latino_DYJetsToLL_M-50_0000__part0.root latino_MetCorrected_data_numEventTest.root
mv latino_MetCorrected_data_numEventTest.root MEtXYcorrWithNvtx_MorionV1_DYJetsToLL_M-50_0000__part0.root
gardener.py  metXYshift -c 809 -p metXYshiftPara_MoriondV1_ftnalPar.txt --sample Run2016BDouble /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW6p3/08Jul2016_Run2016B_PromptReco/l2loose__hadd__EpTCorr__l2tight/latino_Run2016B_PromptReco_SingleMuon.root latino_MetCorrected_data_numEventTest.root
mv latino_MetCorrected_data_numEventTest.root MEtXYcorrWithNvtx_MorionV1_Run2016B_SingleMuon.root
#gardener.py  metXYshift -c 809 -p MoriondDouble_MEtXY_shiftRunB_multiplicity_PfType1Met.txt /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW6p3/08Jul2016_Run2016B_PromptReco/l2loose__hadd__EpTCorr__l2tight/latino_Run2016B_PromptReco_SingleMuon.root latino_MetCorrected_data_numEventTest.root
#mv latino_MetCorrected_data_numEventTest.root MEtXYcorrWithMulti_MorionV1_Run2016B_SingleMuon.root
#gardener.py  metXYshift -c 809 -p Moriond_MEtXY_shiftRunB_multiplicity_PfType1Met.txt /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW6p3/08Jul2016_Run2016B_PromptReco/l2loose__hadd__EpTCorr__l2tight/latino_Run2016B_PromptReco_SingleMuon.root latino_MetCorrected_data_numEventTest.root
#mv latino_MetCorrected_data_numEventTest.root MEtXYcorrWithMulti_MorionV1_Run2016B_SingleMuon.root
#gardener.py  metXYshift -c 809 -p Moriond17V1_MEtXY_shiftRunD_PfType1Met.txt /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW12fb/26Jul2016_Run2016D_PromptReco/l2loose__hadd__ICHEPjson__EpTCorr__l2tight/latino_Run2016D_PromptReco_DoubleMuon.root latino_MetCorrected_data_numEventTest.root
#mv latino_MetCorrected_data_numEventTest.root MEtXYcorr_MorionV1_Run2016D_DoubleMuon.root
#gardener.py  metXYshift -c 809 -p Moriond17V1_MEtXY_shiftRunD_PfType1Met.txt /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW12fb/26Jul2016_Run2016D_PromptReco/l2loose__hadd__ICHEPjson__EpTCorr__l2tight/latino_Run2016D_PromptReco_SingleMuon.root latino_MetCorrected_data_numEventTest.root
#mv latino_MetCorrected_data_numEventTest.root MEtXYcorr_MorionV1_Run2016D_SingleMuon.root
#gardener.py  metXYshift -c 809 -p Moriond17V1_MEtXY_shiftRunC_PfType1Met.txt /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW12fb/11Jul2016_Run2016C_PromptReco/l2loose__hadd__ICHEPjson__EpTCorr__l2tight/latino_Run2016C_PromptReco_SingleMuon.root latino_MetCorrected_data_numEventTest.root
#mv latino_MetCorrected_data_numEventTest.root MEtXYcorr_MorionV1_Run2016C_SingleMuon.root
#gardener.py  metXYshift -c 809 -p Moriond17V1_MEtXY_shiftRunB_PfType1Met.txt /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW6p3/08Jul2016_Run2016B_PromptReco/l2loose__hadd__EpTCorr__l2tight/latino_Run2016B_PromptReco_SingleMuon.root latino_MetCorrected_data_numEventTest.root
#mv latino_MetCorrected_data_numEventTest.root MEtXYcorr_MorionV1_Run2016B_SingleMuon.root


#gardener.py  metXYshift -c 809 -p Summer16_Zmumu_NoZeoro_MEtXY_shiftRun2016CDEFG_sumPt_PfType1Met.txt /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW12fb/11Jul2016_Run2016C_PromptReco/l2loose__hadd__ICHEPjson__EpTCorr__l2tight/latino_Run2016C_PromptReco_SingleMuon.root latino_MetCorrected_data_numEventTest.root
#gardener.py  metXYshift -c 809 -p Summer16_V0_DATA_MEtXY_shiftData_PfType1Met.txt /d1/scratch/sangilpark/Latino_CernBox/80Xv2/HWW12fb/11Jul2016_Run2016C_PromptReco/l2loose__hadd__ICHEPjson__EpTCorr__l2tight/latino_Run2016C_PromptReco_SingleMuon.root latino_MetCorrected_data_numEventTest.root
