# 
# Expanded version of samples.py 
# 
samples['HH'] = { 
     'name'  :  [ 
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_HHWWbblvjj_nevents5k.root',
     ],  
     'weight'  :   'event.baseW*                        event.GEN_weight_SM/abs(event.GEN_weight_SM)                         if hasattr(event, 'GEN_weight_SM') else event.baseW*event.puW*                          event.effTrigW*                          event.std_vector_lepton_recoW[0]*                          event.veto_EMTFBug                           if hasattr(event, 'std_vector_lepton_recoW') else 1.*(event.std_vector_trigger_special[0]*                     event.std_vector_trigger_special[1]*                     event.std_vector_trigger_special[2]*                     event.std_vector_trigger_special[3]*                     event.std_vector_trigger_special[5] )*(((event.std_vector_trigger_special[8]==-2.)*(event.std_vector_trigger_special[6]*event.std_vector_trigger_special[7])) or ((not (event.std_vector_trigger_special[8]==-2.))*(event.std_vector_trigger_special[8]*event.std_vector_trigger_special[9])))' ,
}  
   
 samples['Wjets'] = { 
     'name'  :  [ 
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part0.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part1.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part10.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part11.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part12.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part13.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part14.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part15.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part16.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part17.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part18.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part19.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part2.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part3.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part4.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part5.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part6.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part7.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part8.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT100_200__part9.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part0.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part1.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part10.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part2.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part3.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part4.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part5.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part6.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part7.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part8.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT200_400__part9.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT400_600__part0.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT400_600__part1.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT400_600__part2.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT400_600__part3.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT400_600__part4.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part0.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part1.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part2.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part3.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part4.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part5.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part6.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part7.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT600_800__part8.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part0.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part1.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part10.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part11.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part12.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part13.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part14.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part2.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part3.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part4.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part5.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part6.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part7.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part8.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT800_1200_ext1__part9.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT1200_2500__part0.root',
            '###/gwteraz/users/amassiro/latino/lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC/latino_WJetsToLNu_HT2500_inf__part0.root',
     ],  
     'weight'  :   'event.baseW*                        event.GEN_weight_SM/abs(event.GEN_weight_SM)                         if hasattr(event, 'GEN_weight_SM') else event.baseW*event.puW*                          event.effTrigW*                          event.std_vector_lepton_recoW[0]*                          event.veto_EMTFBug                           if hasattr(event, 'std_vector_lepton_recoW') else 1.*(event.std_vector_trigger_special[0]*                     event.std_vector_trigger_special[1]*                     event.std_vector_trigger_special[2]*                     event.std_vector_trigger_special[3]*                     event.std_vector_trigger_special[5] )*(((event.std_vector_trigger_special[8]==-2.)*(event.std_vector_trigger_special[6]*event.std_vector_trigger_special[7])) or ((not (event.std_vector_trigger_special[8]==-2.))*(event.std_vector_trigger_special[8]*event.std_vector_trigger_special[9])))' ,
     'FilesPerJob'  :   2 ,
}  
   
 