#RAndKff  = {}
RAndKff['DYmva0p8'] = {
                      'RFile'   : 'rootFile/plots_BG_DY_NOHR_MVA080_2j.root' ,
                      'KffFile' : 'rootFile/plots_BG_DY_NOHR_MVA080_2j.root' ,
                      'Regions' : { '2jee' : {
                                               'kNum' : '2j_ee_in/events/histo_DY' ,
                                               'kDen' : '2j_uu_in/events/histo_DY' ,
                                               'RNum' : '2j_ee_out/events/histo_DY' ,
                                               'RDen' : '2j_ee_in/events/histo_DY' ,
                                             } ,
                                    '2jmm' : {
                                               'kNum' : '2j_uu_in/events/histo_DY' ,
                                               'kDen' : '2j_ee_in/events/histo_DY' ,
                                               'RNum' : '2j_uu_out/events/histo_DY' ,
                                               'RDen' : '2j_uu_in/events/histo_DY' ,
                                             } ,
                                   } ,
                     }

#DYestim = {}

DYestim['hww2l2v_13TeV_sf2j_ee_mjj0_350_pth0_60'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.03 ,
                                 'ksyst'   : 0.02 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'ee' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_ee' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYeenorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_ee_mjj0_350_pth0_60/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_ee/events/histo_DY',
                                 'asyst'   : 0.09 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_ee_mjj0_350_pth60_120'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.03 ,
                                 'ksyst'   : 0.02 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'ee' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_ee' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYeenorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_ee_mjj0_350_pth60_120/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_ee/events/histo_DY',
                                 'asyst'   : 0.09 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_ee_mjj0_350_pth120_200'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.03 ,
                                 'ksyst'   : 0.02 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'ee' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_ee' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYeenorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_ee_mjj0_350_pth120_200/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_ee/events/histo_DY',
                                 'asyst'   : 0.09 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_ee_mjj350_700_pthjj0_25'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.03 ,
                                 'ksyst'   : 0.02 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'ee' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_ee' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYeenorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_ee_mjj350_700_pthjj0_25/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_ee/events/histo_DY',
                                 'asyst'   : 0.09 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_ee_mjj350_700_pthjj25'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.03 ,
                                 'ksyst'   : 0.02 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'ee' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_ee' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYeenorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_ee_mjj350_700_pthjj25/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_ee/events/histo_DY',
                                 'asyst'   : 0.09 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_ee_mjj700_pthjj0_25'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.03 ,
                                 'ksyst'   : 0.02 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'ee' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_ee' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYeenorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_ee_mjj700_pthjj0_25/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_ee/events/histo_DY',
                                 'asyst'   : 0.09 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_ee_mjj700_pthjj25'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.03 ,
                                 'ksyst'   : 0.02 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'ee' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_ee' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYeenorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_ee_mjj700_pthjj25/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_ee/events/histo_DY',
                                 'asyst'   : 0.09 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_mm_mjj0_350_pth0_60'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.08 ,
                                 'ksyst'   : 0.04 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'mm' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_mm' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYmmnorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_mm_mjj0_350_pth0_60/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_mm/events/histo_DY',
                                 'asyst'   : 0.03 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_mm_mjj0_350_pth60_120'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.08 ,
                                 'ksyst'   : 0.04 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'mm' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_mm' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYmmnorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_mm_mjj0_350_pth60_120/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_mm/events/histo_DY',
                                 'asyst'   : 0.03 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_mm_mjj0_350_pth120_200'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.08 ,
                                 'ksyst'   : 0.04 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'mm' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_mm' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYmmnorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_mm_mjj0_350_pth120_200/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_mm/events/histo_DY',
                                 'asyst'   : 0.03 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_mm_mjj350_700_pthjj0_25'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.08 ,
                                 'ksyst'   : 0.04 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'mm' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_mm' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYmmnorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_mm_mjj350_700_pthjj0_25/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_mm/events/histo_DY',
                                 'asyst'   : 0.03 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_mm_mjj350_700_pthjj25'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.08 ,
                                 'ksyst'   : 0.04 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'mm' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_mm' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYmmnorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_mm_mjj350_700_pthjj25/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_mm/events/histo_DY',
                                 'asyst'   : 0.03 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_mm_mjj700_pthjj0_25'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.08 ,
                                 'ksyst'   : 0.04 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'mm' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_mm' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYmmnorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_mm_mjj700_pthjj0_25/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_mm/events/histo_DY',
                                 'asyst'   : 0.03 ,
                                }

DYestim['hww2l2v_13TeV_sf2j_mm_mjj700_pthjj25'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'rsyst'   : 0.08 ,
                                 'ksyst'   : 0.04 ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'mm' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_mm' ,
                                 'SFinDa'  : 'DATA' ,
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYmmnorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_HAccNum_sf2j_mm_mjj700_pthjj25/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_mm/events/histo_DY',
                                 'asyst'   : 0.03 ,
                                }

DYestim['hww2l2v_13TeV_2016_WW_2j_ee'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'ee' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_ee' ,
                                 'SFinDa'  : 'DATA',
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYeenorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_2016_hww2l2v_13TeV_wwAcc_2j_ee/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_ee/events/histo_DY',
                                 'asyst'   : 0.03 ,
                                   }

DYestim['hww2l2v_13TeV_2016_WW_2j_mm'] = {
                                 'rinout'  : 'DYmva0p8' ,
                                 'njet'    : '2j'    ,
                                 'flavour' : 'mm' ,
                                 'DYProc'  : 'DY' ,
                                 'SFin'    : 'hww2l2v_13TeV_DYin_2j_mm' ,
                                 'SFinDa'  : 'DATA',
                                 'SFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'DFin'    : 'hww2l2v_13TeV_DYin_2j_df' ,
                                 'DFinDa'  : 'DATA' ,
                                 'DFinMC'  : ['VZ','Vg','VgS_L','VgS_H'],
                                 'NPname'  : 'DYmmnorm2j' ,
                                 'AccNum'  : 'hww2l2v_13TeV_2016_hww2l2v_13TeV_wwAcc_2j_mm/events/histo_DY',
                                 'AccDen'  : 'hww2l2v_13TeV_AccDen_2j_mm/events/histo_DY',
                                 'asyst'   : 0.01 ,
                                   }

