#/afs/cern.ch/user/t/tkello/workspace/MainAnalysis/HWW_AC/CMSSW_10_6_27/src/LatinoAnalysis/ShapeAnalysis/python/PlotFactory.py

mkPlot.py --pycfg=configuration_Hgg_2016_of2j_ana_unblinded.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH16_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=2.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2016_of2j_ana_unblinded.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH16_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=2.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2017_of2j_ana_unblinded.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH17_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=2.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2017_of2j_ana_unblinded.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH17_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=2.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2018_of2j_ana_unblinded.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH18_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=2.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2018_of2j_ana_unblinded.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH18_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=2.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_Run2_of2j_ana_unblinded.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJHRun2_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=2.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_Run2_of2j_ana_unblinded.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJHRun2_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=2.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"

#LOG
mkPlot.py --pycfg=configuration_Hgg_2016_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH16_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2016_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH16_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2017_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH17_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2017_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH17_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2018_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH18_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2018_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJH18_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_Run2_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJHRun2_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_Run2_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files/plots_JJHRun2_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"

#LOG for rebinned input
mkPlot.py --pycfg=configuration_Hgg_2016_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files_rebin/plots_JJH16_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2016_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files_rebin/plots_JJH16_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2017_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files_rebin/plots_JJH17_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2017_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files_rebin/plots_JJH17_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2018_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files_rebin/plots_JJH18_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_2018_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files_rebin/plots_JJH18_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_Run2_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files_rebin/plots_JJHRun2_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmin --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} < 0@@Prefit"
mkPlot.py --pycfg=configuration_Hgg_Run2_of2j_ana_unblinded_log.py --showIntegralLegend=1 --onlyPlot=cratio --inputFile=Files_rebin/plots_JJHRun2_H0M.root --onlyCut hww2l2v_13TeV_of2j_ggh_thmip --fileFormats="png,pdf" --onlyVariable HGG_H0M --minLogCratio=1.1 --scaleToPlot=3.0 --extraLegend="[D_{VBF}, D_{0-}^{ggH}]@@ggH 2-jet@@D_{CP}^{ggH} > 0@@Prefit"



