# 
# Expanded version of samples.py 
# 
samples['ChMisId'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-10to50.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part10.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part11.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part12.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part13.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part14.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part15.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part3.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part4.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part5.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part6.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part7.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part8.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_DYJetsToLL_M-50__part9.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_GluGluWWTo2L2Nu_MCFM.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_WWTo2L2Nu.root',
     ],  
     'weights'  :  [ 
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)',
            '(1.)',
     ],  
     'weight'  :   'baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*chargeFlipW*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1]) != -11*11 || (std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1]) != -11*13 )' ,
     'FilesPerJob'  :   2 ,
}  
   
 samples['ttbar'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part10.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part11.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part12.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part13.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part14.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part15.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part16.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part17.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part3.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part4.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part5.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part6.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part7.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part8.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_TTTo2L2Nu__part9.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_ST_tW_top_noHad.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__chMisId__tightVbsSel//latino_ST_tW_antitop_noHad.root',
     ],  
     'weight'  :   'baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*chargeFlipW*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1]) != -11*11 || (std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1]) != -11*13 )' ,
     'FilesPerJob'  :   6 ,
}  
   
 samples['DY_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-10to50.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part10.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part11.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part12.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part13.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part14.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part15.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part3.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part4.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part5.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part6.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part7.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part8.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_DYJetsToLL_M-50__part9.root',
     ],  
     'weights'  :  [ 
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
            '(1.)*((1.08683 * (0.95 - 0.0657370*TMath::Erf((gen_ptll-12.5151)/5.51582))))',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['lep_TT_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part10.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part11.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part12.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part13.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part14.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part15.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part16.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part17.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part3.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part4.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part5.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part6.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part7.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part8.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTTo2L2Nu__part9.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
     'FilesPerJob'  :   6 ,
}  
   
 samples['singleTop_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_ST_tW_top_noHad.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['singleAntiTop_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_ST_tW_antitop_noHad.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['ggWWTo2L2Nu_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_GluGluWWTo2L2Nu_MCFM.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['WWTo2L2Nu_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WWTo2L2Nu.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['Vg_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WGJJ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_Zg__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_Zg__part1.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['ZZ_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_ZZTo4L__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_ZZTo4L__part1.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['WpWpJJ_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WpWpJJ_EWK.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WmWmJJ_EWK_powheg.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)*1.067466' ,
}  
   
 samples['WpWpJJ_QCD_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WpWpJJ_QCD.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)*1.057' ,
}  
   
 samples['VVV_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WZZ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_ZZZ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WWW.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WWZ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTZToQQ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTWJetsToQQ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTWJetsToLNu.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_TTZToLLNuNu_M-10.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['DPS_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WWTo2L2Nu_DoubleScattering.root',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['WZ_promptSubtr'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_tZq_ll__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_tZq_ll__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_tZq_ll__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_tZq_ll__part3.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_tZq_ll__part4.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-4To50_QCD_2Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-50_QCD_1Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-4To50_QCD_1Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-50_QCD_2Jet__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-50_QCD_2Jet__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WZTo3LNu.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-60_EWK_4F.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-50_QCD_0Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-4To50_QCD_3Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-4To60_EWK_4F.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-50_QCD_3Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__tightVbsSel__bkgWeights//latino_WLLJJToLNu_M-4To50_QCD_0Jet.root',
     ],  
     'weights'  :  [ 
            '1.',
            '1.',
            '1.',
            '1.',
            '1.',
            '1.206',
            '1.206',
            '1.206',
            '1.206',
            '1.206',
            '1',
            '1.',
            '1.206',
            '1.206',
            '1.',
            '1.206',
            '1.206',
     ],  
     'weight'  :   '-1.*fakeW2l*baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
     'FilesPerJob'  :   6 ,
}  
   
 samples['Vg'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_Zg__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_Zg__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WGJJ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_Wg_MADGRAPHMLM.root',
     ],  
     'weight'  :   'baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['ZZ'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_ZZTo4L__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_ZZTo4L__part1.root',
     ],  
     'weight'  :   'baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
     'FilesPerJob'  :   6 ,
}  
   
 samples['WZ'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_tZq_ll__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_tZq_ll__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_tZq_ll__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_tZq_ll__part3.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_tZq_ll__part4.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-4To50_QCD_2Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-50_QCD_1Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-4To50_QCD_1Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-50_QCD_2Jet__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-50_QCD_2Jet__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WZTo3LNu.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-60_EWK_4F.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-50_QCD_0Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-4To50_QCD_3Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-4To60_EWK_4F.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-50_QCD_3Jet.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WLLJJToLNu_M-4To50_QCD_0Jet.root',
     ],  
     'weights'  :  [ 
            '1.',
            '1.',
            '1.',
            '1.',
            '1.',
            '1.206',
            '1.206',
            '1.206',
            '1.206',
            '1.206',
            '1',
            '1.',
            '1.206',
            '1.206',
            '1.',
            '1.206',
            '1.206',
     ],  
     'weight'  :   'baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
     'FilesPerJob'  :   6 ,
}  
   
 samples['VVV'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_ZZZ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WZZ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WWZ.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WWW.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_TTWJetsToLNu.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_TTZToLLNuNu_M-10.root',
     ],  
     'weight'  :   'baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['DPS'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WWTo2L2Nu_DoubleScattering.root',
     ],  
     'weight'  :   'baseW*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
}  
   
 samples['WW_strong'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WpWpJJ_QCD.root',
     ],  
     'weight'  :   'baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)*1.057' ,
     'FilesPerJob'  :   1 ,
}  
   
 samples['WW_EWK'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_summer16/lep2SelVBS__MCWeights__hadd__bSFL2pTEffCut__genMatchVariables__l2tightVBS__tightVbsSel//latino_WpWpJJ_EWK.root',
     ],  
     'weight'  :   'baseW*GEN_weight_SM/abs(GEN_weight_SM)*puW*effTrigW*bPogSF_CSVM*std_vector_lepton_recoW[0]*std_vector_lepton_recoW[1]*std_vector_lepton_idisoWcut_WP_Tight80X[0]*std_vector_lepton_idisoWcut_WP_Tight80X[1]*std_vector_lepton_promptgenmatched[0]*std_vector_lepton_promptgenmatched[1]*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(((std_vector_trigger_special[8]==-2.)*(std_vector_trigger_special[6]*std_vector_trigger_special[7])) || ((! (std_vector_trigger_special[8]==-2.))*(std_vector_trigger_special[8]*std_vector_trigger_special[9])))*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)*1.067466' ,
     'FilesPerJob'  :   1 ,
}  
   
 samples['Fake_lep'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_MuonEG_Run2016B-03Feb2017_ver2-v2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_MuonEG_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_MuonEG_Run2016D-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016D-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016D-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016D-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016D-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016D-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016D-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_MuonEG_Run2016E-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016E-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016E-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016E-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016E-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016E-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016E-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_MuonEG_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_MuonEG_Run2016G-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016G-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016G-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016G-03Feb2017-v1__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016G-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016G-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016G-03Feb2017-v1__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016G-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016G-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016G-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016G-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_MuonEG_Run2016H-03Feb2017_ver2-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_MuonEG_Run2016H-03Feb2017_ver3-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleMuon_Run2016H-03Feb2017_ver3-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleMuon_Run2016H-03Feb2017_ver3-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_DoubleEG_Run2016H-03Feb2017_ver3-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__tightVbsSel__bkgWeights//latino_SingleElectron_Run2016H-03Feb2017_ver3-v1.root',
     ],  
     'weights'  :  [ 
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
     ],  
     'isData'  :  [ 
            'all',
     ],  
     'weight'  :   'fakeW2l*(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(std_vector_trigger_special[4]*                                              (! std_vector_trigger_special[6])*                                              (! std_vector_trigger_special[7])*                                              std_vector_trigger_special[8]*                                              std_vector_trigger_special[9])*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
     'FilesPerJob'  :   6 ,
}  
   
 samples['DATA'] = { 
     'name'  :  [ 
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_MuonEG_Run2016B-03Feb2017_ver2-v2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016B-03Feb2017_ver2-v2__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016B_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016B-03Feb2017_ver2-v2__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_MuonEG_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016C_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016C-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_MuonEG_Run2016D-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016D-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016D-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016D-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016D-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016D-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016D_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016D-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_MuonEG_Run2016E-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016E-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016E-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016E-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016E-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016E-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016E_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016E-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_MuonEG_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016F_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016F-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_MuonEG_Run2016G-03Feb2017-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016G-03Feb2017-v1__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016G-03Feb2017-v1__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016G-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016G-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016G-03Feb2017-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016G_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016G-03Feb2017-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_MuonEG_Run2016H-03Feb2017_ver2-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016H-03Feb2017_ver2-v1__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016H-03Feb2017_ver2-v1__part2.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016H-03Feb2017_ver2-v1__part0.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016H-03Feb2017_ver2-v1__part1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_MuonEG_Run2016H-03Feb2017_ver3-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleMuon_Run2016H-03Feb2017_ver3-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleMuon_Run2016H-03Feb2017_ver3-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_DoubleEG_Run2016H-03Feb2017_ver3-v1.root',
            '###/gwteras/cms/store/group/OneLepton/Apr2017_Run2016H_RemAOD/lep2SelVBS__hadd__EpTCorr__TrigMakerData__l2tightVBS__tightVbsSel//latino_SingleElectron_Run2016H-03Feb2017_ver3-v1.root',
     ],  
     'weights'  :  [ 
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
            ' trig_EleMu',
            '!trig_EleMu &&  trig_DbleMu',
            '!trig_EleMu && !trig_DbleMu &&  trig_SnglMu',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu &&  trig_DbleEle',
            '!trig_EleMu && !trig_DbleMu && !trig_SnglMu && !trig_DbleEle &&  trig_SnglEle',
     ],  
     'isData'  :  [ 
            'all',
     ],  
     'weight'  :   '(std_vector_trigger_special[0]*                     std_vector_trigger_special[1]*                     std_vector_trigger_special[2]*                     std_vector_trigger_special[3]*                     std_vector_trigger_special[5]                   )*(std_vector_trigger_special[4]*                                              (! std_vector_trigger_special[6])*                                              (! std_vector_trigger_special[7])*                                              std_vector_trigger_special[8]*                                              std_vector_trigger_special[9])*((std_vector_lepton_flavour[0] * std_vector_lepton_flavour[1])>0)' ,
     'FilesPerJob'  :   6 ,
}  
   
 